/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-02 13:32:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.mypage_002djin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class withdrawal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/templates/mypage-jin/../mainpageSeo/loginHeader.jsp", Long.valueOf(1683004062648L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"../../static/image/logo/logo.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("<title>계정 탈퇴</title>\n");
      out.write("<!--폰트 -->\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("	\n");
      out.write("	\n");
      out.write("<link href=\"../../static/css/mypage-css-jin/withdrawal.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- 로고 -->\n");
      out.write("<link href=\"../../static/image/logo/logo.png\" rel=\"shortcut icon\"\n");
      out.write("	type=\"image/x-icon\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("	href=\"../../static/css/mainpageSeo/hf.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<body class=\"home\">\n");
      out.write("	<div class=\"h__cov-progress\"\n");
      out.write("		style=\"background-color: rgb(0, 199, 174); opacity: 0; position: fixed; top: 0px; left: 0px; width: 0%; height: 2px; transition: opacity 0.6s ease 0s;\"></div>\n");
      out.write("	<header id=\"app-header\" class=\"h_global-header\" data-v-50506024=\"\">\n");
      out.write("		<div  data-v-50506024=\"\"\n");
      out.write("			class=\"h-global-navigation-bar\">\n");
      out.write("			<!-- 섹션태그때문에 이미지가 나오지 않아서 없애버렸어요 -->\n");
      out.write("			<div  class=\"h-desktop-header\">\n");
      out.write("				<div  class=\"left-section\" style=\"display: flex; margin-right: 300px\">\n");
      out.write("					<div  class=\"logo\" style=\"margin: auto;\">\n");
      out.write("						<a  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listOk.board\" class=\"\"> <img\n");
      out.write("							 src=\"../../static/image/logo/JOONGSHIN.svg\"\n");
      out.write("							alt=\"숨고, 숨은고수\">\n");
      out.write("						</a>\n");
      out.write("					</div>\n");
      out.write("						<ul class=\"nav-list\" style=\"margin-right: 20px;\">\n");
      out.write("							<li  class=\"nav-item left-section-item\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/comulistOk.board\">\n");
      out.write("								<span>커뮤니티</span></li></a>\n");
      out.write("							<li class=\"nav-item left-section-item\"><a\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reqBoard.board\">\n");
      out.write("								<span >문의 게시판</span></a></li>\n");
      out.write("						</ul>\n");
      out.write("				</div>\n");
      out.write("				<!--  					 로고,문자열 네개까지 ↑ -->\n");
      out.write("				");
      out.write("\n");
      out.write("				<!-- 로그인 회원가입 고수가입 전↑ -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				<div  class=\"right-section\" style=\"display: flex; margin-left: 20px;\">\n");
      out.write("					<nav >\n");
      out.write("						<ul  class=\"nav-list\">\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/messageListOk.message\"\n");
      out.write("							class=\"message1\" name=\"message\" style=\"font-size: 17px; margin: auto;\">\n");
      out.write("							<li  class=\"nav-item right-section-item\"><span \n");
      out.write("									>채팅</span>\n");
      out.write("							<!----></li>\n");
      out.write("							</a>\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myMainOk.mypage\"\n");
      out.write("							class=\"mypage1\" name=\"search-form\" style=\"margin: auto 40px;\">\n");
      out.write("							<li  class=\"nav-item right-section-item\" >\n");
      out.write("							<span style=\"font-size: 17px;\"\n");
      out.write("									>마이페이지</span>\n");
      out.write("							<!----></li>\n");
      out.write("							</form>\n");
      out.write("							</a>\n");
      out.write("							<li  class=\"nav-item right-section-item\">\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.user\"><span style=\"font-size: 17px;\"\n");
      out.write("									>로그아웃</span></a>\n");
      out.write("							<!----></li>\n");
      out.write("						</ul>\n");
      out.write("					</nav>\n");
      out.write("					\n");
      out.write("					\n");
      out.write("						\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<!-- 헤더 전체 div 닫는부분 -->\n");
      out.write("			<!-- 없애버린 세션 태그 닫는자리 -->\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("	<!-- 헤더 끝 -->\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div id=\"app-body\">\n");
      out.write("		<div class=\"container container-md\">\n");
      out.write("			<main class=\"account-info-container\">\n");
      out.write("				<h1>계정 탈퇴</h1>\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myWithdrawalOk.mypage\" name=\"deleteUser\" method=\"post\">\n");
      out.write("				<section>\n");
      out.write("					<article>\n");
      out.write("						<h3>숨고 탈퇴 전 꼭 확인해 주세요</h3>\n");
      out.write("						<div class=\"check-list\">\n");
      out.write("							<ol>\n");
      out.write("								<li>탈퇴시 모든 개인정보가 삭제되며, 구매하신 캐시는 소멸되며 환불되지 않습니다.</li>\n");
      out.write("								<li>숨고 이용에 불편이 있어 탈퇴를 고민하신다면, support@joongshin.com 또는 <span\n");
      out.write("									class=\"color-teal\">1599-0000</span>로 문의 바랍니다.\n");
      out.write("								</li>\n");
      out.write("								<li>위 내용을 모두 확인하였고, 탈퇴 완료 시 내용에 동의합니다.</li>\n");
      out.write("							</ol>\n");
      out.write("						</div>\n");
      out.write("					</article>\n");
      out.write("\n");
      out.write("					<article>\n");
      out.write("						<h3>탈퇴 사유</h3>\n");
      out.write("						<ul data-testid=\"delete-answer-section\" class=\"answer-section\">\n");
      out.write("							<li class=\"answer-item\" style=\"border: 0px;\"><div class=\"radio-group\">\n");
      out.write("									<div id=\"nav\">\n");
      out.write("										<label class=\"check\"\n");
      out.write("										for=\"radio-text-0\"><input type=\"radio\" name=\"radio-button\" id=\"radio-button-1\">\n");
      out.write("										<span class=\"text\"> 알림이 너무 많이 와요 </span></label>\n");
      out.write("									<div id=\"hidden-div-1\" class=\"description-wrapper\" style=\"display: none;\">\n");
      out.write("										<span data-v-30a01857=\"\">너무 많은 알림을 받는다면, <span\n");
      out.write("											class=\"color-teal\">알림설정</span>에서 알림 제한 시간을 정할 수 있어요.\n");
      out.write("										</span>\n");
      out.write("									</div>\n");
      out.write("								</div></li>\n");
      out.write("							<li class=\"answer-item menu\" style=\"border: 0px;\"><div class=\"radio-group\">\n");
      out.write("										<label class=\"check\" for=\"radio-text-0\"><input type=\"radio\" name=\"radio-button\" id=\"radio-button-2\">\n");
      out.write("										<span class=\"radio\"></span><span class=\"text\"> 사용하기 어려워요 </span></label>\n");
      out.write("									<div id=\"hidden-div-2\" class=\"description-wrapper\" style=\"display: none;\">\n");
      out.write("										<span data-v-30a01857=\"\">어떤 부분에서 사용이 어려우신가요?<br> \n");
      out.write("										<span class=\"color-teal\">고객센터\n");
      out.write("										</span>에 문의해주시면 자세하게 알려드릴게요.\n");
      out.write("										</span>\n");
      out.write("									</div>\n");
      out.write("								</div></li>\n");
      out.write("							<li class=\"answer-item menu\" style=\"border: 0px;\"><div class=\"radio-group\">\n");
      out.write("										<label class=\"check\"\n");
      out.write("										for=\"radio-text-0\"><input type=\"radio\" name=\"radio-button\" id=\"radio-button-3\">\n");
      out.write("											</span><span class=\"text\"> 오류가 많아서 불편해요 </span></label>\n");
      out.write("									<div id=\"hidden-div-3\" class=\"description-wrapper\" style=\"display: none;\">\n");
      out.write("										<span data-v-30a01857=\"\">불편사항을 <span class=\"color-teal\">고객센터\n");
      out.write("										</span>에 알려주시면 최대한 빨리 해결해드릴게요.\n");
      out.write("										</span>\n");
      out.write("									</div>\n");
      out.write("								</div></li>\n");
      out.write("							<li class=\"answer-item menu\" style=\"border: 0px;\"><div class=\"radio-group\">\n");
      out.write("									<label class=\"check\"\n");
      out.write("										for=\"radio-text-0\"><input type=\"radio\" name=\"radio-button\" id=\"radio-button-4\">\n");
      out.write("											<span class=\"radio\"></span><span\n");
      out.write("										class=\"text\"> 기타 </span></label>\n");
      out.write("									<div id=\"hidden-div-4\" class=\"description-wrapper\" style=\"display: none;\">\n");
      out.write("										<textarea data-v-30a01857=\"\" name=\"accountDeleteReason\"\n");
      out.write("											placeholder=\"떠나게 되어 아쉽네요. 이유를 자세히 알려주실 수 있나요?\" rows=\"2\"\n");
      out.write("											wrap=\"soft\" class=\"textarea form-control\"\n");
      out.write("											data-testid=\"account-delete-reason\"\n");
      out.write("											data-vv-validate-on=\"blur\" maxlength=\"500\"\n");
      out.write("											aria-invalid=\"false\" id=\"__BVID__423\"></textarea>\n");
      out.write("										<div data-v-30a01857=\"\" class=\"description-wrapper\"\n");
      out.write("											style=\"display: none;\">\n");
      out.write("											<span data-v-30a01857=\"\" class=\"validation-text\"></span>\n");
      out.write("										</div>\n");
      out.write("										<div data-v-30a01857=\"\" class=\"textarea-length\">\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div></li>\n");
      out.write("						</ul>\n");
      out.write("						</article>\n");
      out.write("						<div class=\"validation-wrapper\" style=\"display: none;\">\n");
      out.write("							<span class=\"validation-text\">탈퇴 사유를 선택해주세요.</span>\n");
      out.write("						</div>\n");
      out.write("					</section>\n");
      out.write("					<footer class=\"button-group\">\n");
      out.write("						<a href=\"javascript:history.go(-1)\"\n");
      out.write("							class=\"btn router-link-active btn-outline-primary\" target=\"_self\" style=\"color: #6FB6C0;\" >취소</a>\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary submit-btn\" onclick=\"submitDelete()\">탈퇴 완료</button>\n");
      out.write("					</footer>\n");
      out.write("				</form>\n");
      out.write("			</main>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../mainpageSeo/footer.jsp", out, false);
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("	/* 버튼 클릭하면 숨겨져있는 요소들 보임 */\n");
      out.write("	const radioButtons = document.getElementsByName(\"radio-button\");\n");
      out.write("	const hiddenDivs = document.querySelectorAll('[id^=\"hidden-div-\"]');\n");
      out.write("\n");
      out.write("	var checkTarget;\n");
      out.write("	console.log(checkTarget);\n");
      out.write("\n");
      out.write("	for (let i = 0; i < radioButtons.length; i++) {\n");
      out.write("	  radioButtons[i].addEventListener(\"click\", function() {\n");
      out.write("	  checkTarget = radioButtons[i];\n");
      out.write("	  console.log(checkTarget);\n");
      out.write("	    for (let j = 0; j < hiddenDivs.length; j++) {\n");
      out.write("	      if (hiddenDivs[j].id === \"hidden-div-\" + (i+1)) {\n");
      out.write("	        hiddenDivs[j].style.display = \"block\";\n");
      out.write("	      } else {\n");
      out.write("	        hiddenDivs[j].style.display = \"none\";\n");
      out.write("	      }\n");
      out.write("	    }\n");
      out.write("	  });\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function submitDelete() {\n");
      out.write("		if(checkTarget) {\n");
      out.write("			document.deleteUser.submit();\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
