/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 05:36:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.mainpageSeo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1681825652000L));
    _jspx_dependants.put("jar:file:/Users/gimjin/Desktop/web_1900_hds/jsp/workspace/joongshin/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/templates/mainpageSeo/footer.jsp", Long.valueOf(1682517413499L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--  listOk.board -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("	href=\"../../static/css/mainpageSeo/main-page.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<!-- 로고 -->\n");
      out.write("<link href=\"../../static/image/logo/logo.png\" rel=\"shortcut icon\"\n");
      out.write("	type=\"image/x-icon\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/mainpageSeo/board.css\">\n");
      out.write("\n");
      out.write("<title>중신:주니어의 스펙업사이트</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".content-container {\n");
      out.write("	padding: 10px;\n");
      out.write("	border-radius: 10px;\n");
      out.write("	background-color: #f1f1f1;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".content {\n");
      out.write("	display: block;\n");
      out.write("	overflow: hidden;\n");
      out.write("	text-overflow: ellipsis;\n");
      out.write("	white-space: nowrap;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div id=\"app-body\">\n");
      out.write("		<div class=\"home\" data-v-38e68602=\"\">\n");
      out.write("\n");
      out.write("			<!-- 배너 -->\n");
      out.write("			<section class=\"banner-container\">\n");
      out.write("			<div class=\"banner\">\n");
      out.write("				<div id=\"first-temp\"></div>\n");
      out.write("				<div class=\"image\"></div>\n");
      out.write("				<div class=\"image\"></div>\n");
      out.write("				<div class=\"image\"></div>\n");
      out.write("				<div class=\"image\"></div>\n");
      out.write("				<div class=\"image\"></div>\n");
      out.write("				<div class=\"image\"></div>\n");
      out.write("				<div id=\"last-temp\"></div>\n");
      out.write("			</div>\n");
      out.write("			<button class=\"arrow prev\"></button>\n");
      out.write("			<button class=\"arrow next\"></button>\n");
      out.write("			<div class=\"page-number\"></div>\n");
      out.write("			</section>\n");
      out.write("			<!-- 배너 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			</section>\n");
      out.write("\n");
      out.write("			<!--주니어 커뮤니티  -->\n");
      out.write("			<section id=\"info-wrap\">\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"main-community slide-knowhow-list container\"\n");
      out.write("				data-v-0b8ae29e=\"\" data-v-2590092d=\"\">\n");
      out.write("				<section class=\"header short-bottom\" data-v-0b8ae29e=\"\">\n");
      out.write("				<h2 class=\"title\" data-v-0b8ae29e=\"\">게시판 목록</h2>\n");
      out.write("\n");
      out.write("				<a\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/comulistOk.board\"\n");
      out.write("					data-testid=\"community-home\" class=\"go-list\" data-v-1b5b0368=\"\"\n");
      out.write("					data-v-0b8ae29e=\"\"><span data-v-1b5b0368=\"\">전체보기</span><img\n");
      out.write("					src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPGc+CiAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgPGc+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZD0iTTAgMEgxNlYxNkgweiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTEwNTMuMDAwMDAwLCAtMjAyLjAwMDAwMCkgdHJhbnNsYXRlKDQ4NS4wMDAwMDAsIDE4OC4wMDAwMDApIHRyYW5zbGF0ZSg1NjguMDAwMDAwLCAxNC4wMDAwMDApIi8+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggc3Ryb2tlPSIjMDBDN0FFIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS13aWR0aD0iMS41IiBkPSJNMTEgMTNMNiA4IDExIDMiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDUzLjAwMDAwMCwgLTIwMi4wMDAwMDApIHRyYW5zbGF0ZSg0ODUuMDAwMDAwLCAxODguMDAwMDAwKSB0cmFuc2xhdGUoNTY4LjAwMDAwMCwgMTQuMDAwMDAwKSB0cmFuc2xhdGUoOC41MDAwMDAsIDguMDAwMDAwKSBzY2FsZSgtMSwgMSkgdHJhbnNsYXRlKC04LjUwMDAwMCwgLTguMDAwMDAwKSIvPgogICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4K\"\n");
      out.write("					data-v-1b5b0368=\"\"></a></section>\n");
      out.write("				<div data-v-292a6694=\"\" data-v-0b8ae29e=\"\"\n");
      out.write("					class=\"main-community-contents\">\n");
      out.write("					<h6 class=\"info\">전체 게시글 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개</h6>\n");
      out.write("					<div data-v-292a6694=\"\" class=\"desktop-section\">\n");
      out.write("						<div data-v-292a6694=\"\" class=\"curation-container half-list\"\n");
      out.write("							id=\"content-wrap\">\n");
      out.write("\n");
      out.write("							<!-- 게시글 들어오는곳 -->\n");
      out.write("							<section id=\"content-wrap\">\n");
      out.write("							<ul>\n");
      out.write("							</ul>\n");
      out.write("							</section>\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<div data-v-292a6694=\"\" class=\"knowhow-container half-list\">\n");
      out.write("							<a data-v-292a6694=\"\"\n");
      out.write("								href=\"/community/pro-knowhow/760-%EC%A0%88%EB%8C%80---%EC%9D%B4%EA%B1%B0-%EB%AA%A8%EB%A5%B4%EA%B3%A0-%ED%94%BC%EC%95%84%EB%85%B8-%EC%B9%98%EC%A7%80-%EB%A7%88%EC%84%B8%EC%9A%94\"\n");
      out.write("								class=\"knowhow-card-slide\" data-testid=\"knowhow-item\"><img\n");
      out.write("								data-v-292a6694=\"\" alt=\"절대!! 이거 모르고 피아노 치지 마세요\"\n");
      out.write("								class=\"thumb-image\"\n");
      out.write("								data-src=\"https://static.cdn.soomgo.com/upload/talkboard/b639505d-06da-4b95-bb3e-7521967d8383.jpeg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								src=\"https://static.cdn.soomgo.com/upload/talkboard/b639505d-06da-4b95-bb3e-7521967d8383.jpeg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								lazy=\"loaded\">\n");
      out.write("								<div data-v-292a6694=\"\" class=\"card-desc\">\n");
      out.write("									<p data-v-292a6694=\"\" class=\"service\">피아노/키보드 레슨</p>\n");
      out.write("									<div data-v-a3afae98=\"\" data-v-292a6694=\"\" class=\"collapsed\">\n");
      out.write("										<div data-v-a3afae98=\"\" class=\"line-clamp\"\n");
      out.write("											style=\"line-height: 1.5; max-height: 3rem; -webkit-line-clamp: 2;\">\n");
      out.write("											<p data-v-292a6694=\"\" data-v-a3afae98=\"\" class=\"title\">절대!!\n");
      out.write("												이거 모르고 피아노 치지 마세요</p>\n");
      out.write("										</div>\n");
      out.write("										<!---->\n");
      out.write("									</div>\n");
      out.write("									<p data-v-292a6694=\"\" class=\"author\">취미 전문 레슨, 세달피아노</p>\n");
      out.write("								</div></a> <a data-v-292a6694=\"\"\n");
      out.write("								href=\"/community/pro-knowhow/759-%EB%B3%B4%EB%93%9C%EB%A5%BC-%EC%9E%98-%ED%83%80%EA%B8%B0-%EC%9C%84%ED%95%9C-%EA%BF%80%ED%8C%81\"\n");
      out.write("								class=\"knowhow-card-slide\" data-testid=\"knowhow-item\"><img\n");
      out.write("								data-v-292a6694=\"\" alt=\"보드를 잘 타기 위한 꿀팁\" class=\"thumb-image\"\n");
      out.write("								data-src=\"https://static.cdn.soomgo.com/upload/talkboard/ca7c81f2-5199-4fd2-8fe1-d76bf7aace94.jpg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								src=\"https://static.cdn.soomgo.com/upload/talkboard/ca7c81f2-5199-4fd2-8fe1-d76bf7aace94.jpg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								lazy=\"loaded\">\n");
      out.write("							<div data-v-292a6694=\"\" class=\"card-desc\">\n");
      out.write("									<p data-v-292a6694=\"\" class=\"service\">스노우보드 강습</p>\n");
      out.write("									<div data-v-a3afae98=\"\" data-v-292a6694=\"\" class=\"collapsed\">\n");
      out.write("										<div data-v-a3afae98=\"\" class=\"line-clamp\"\n");
      out.write("											style=\"line-height: 1.5; max-height: 3rem; -webkit-line-clamp: 2;\">\n");
      out.write("											<p data-v-292a6694=\"\" data-v-a3afae98=\"\" class=\"title\">보드를\n");
      out.write("												잘 타기 위한 꿀팁</p>\n");
      out.write("										</div>\n");
      out.write("										<!---->\n");
      out.write("									</div>\n");
      out.write("									<p data-v-292a6694=\"\" class=\"author\">김광현</p>\n");
      out.write("								</div></a> <a data-v-292a6694=\"\"\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/templates/community-users-wmoon/community-main.jsp\"\n");
      out.write("								class=\"knowhow-card-slide\" data-testid=\"knowhow-item\"\n");
      out.write("								><img data-v-292a6694=\"\"\n");
      out.write("								alt=\"이직 면접 이거 놓치면 불합격!\" class=\"thumb-image\"\n");
      out.write("								data-src=\"https://static.cdn.soomgo.com/upload/talkboard/daa7675e-e26d-4a0e-ac1f-ad53dc98a46a.png?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								src=\"https://static.cdn.soomgo.com/upload/talkboard/daa7675e-e26d-4a0e-ac1f-ad53dc98a46a.png?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								lazy=\"loaded\">\n");
      out.write("								<div data-v-292a6694=\"\" class=\"card-desc\">\n");
      out.write("									<p data-v-292a6694=\"\" class=\"service\">(광고)면접 컨설팅</p>\n");
      out.write("									<div data-v-a3afae98=\"\" data-v-292a6694=\"\" class=\"collapsed\">\n");
      out.write("										<div data-v-a3afae98=\"\" class=\"line-clamp\"\n");
      out.write("											style=\"line-height: 1.5; max-height: 3rem; -webkit-line-clamp: 2;\">\n");
      out.write("											<p data-v-292a6694=\"\" data-v-a3afae98=\"\" class=\"title\">이직\n");
      out.write("												면접 이거 놓치면 불합격!</p>\n");
      out.write("										</div>\n");
      out.write("										<!---->\n");
      out.write("									</div>\n");
      out.write("									<p data-v-292a6694=\"\" class=\"author\">김주호</p>\n");
      out.write("								</div></a> <a data-v-292a6694=\"\"\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/templates/community-users-wmoon/community-main.jsp\"\n");
      out.write("								class=\"knowhow-card-slide\" data-testid=\"knowhow-item\"><img\n");
      out.write("								data-v-292a6694=\"\" alt=\"곰팡이 제거, 광고처럼 셀프로 가능할까?\"\n");
      out.write("								class=\"thumb-image\"\n");
      out.write("								data-src=\"https://static.cdn.soomgo.com/upload/talkboard/8a64d04d-c5c6-4cc3-96af-2f1b8875f32a.jpg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								src=\"https://static.cdn.soomgo.com/upload/talkboard/8a64d04d-c5c6-4cc3-96af-2f1b8875f32a.jpg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("								lazy=\"loaded\">\n");
      out.write("								<div data-v-292a6694=\"\" class=\"card-desc\">\n");
      out.write("									<p data-v-292a6694=\"\" class=\"service\">(광고)곰팡이 제거</p>\n");
      out.write("									<div data-v-a3afae98=\"\" data-v-292a6694=\"\" class=\"collapsed\">\n");
      out.write("										<div data-v-a3afae98=\"\" class=\"line-clamp\"\n");
      out.write("											style=\"line-height: 1.5; max-height: 3rem; -webkit-line-clamp: 2;\">\n");
      out.write("											<p data-v-292a6694=\"\" data-v-a3afae98=\"\" class=\"title\">곰팡이\n");
      out.write("												제거, 광고처럼 셀프로 가능할까?</p>\n");
      out.write("										</div>\n");
      out.write("										<!---->\n");
      out.write("									</div>\n");
      out.write("									<p data-v-292a6694=\"\" class=\"author\">도배르만(곰팡이, 단열 전문)</p>\n");
      out.write("								</div></a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- 이용자 게시글 닫는태그 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"observer-container container no-mobile-padding\"\n");
      out.write("				data-v-45a9f2fc=\"\" data-v-73846ecc=\"\" data-v-38e68602=\"\">\n");
      out.write("				<!---->\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!--이용자 커뮤니티  --> <!--\n");
      out.write("<div class=\"main-community slide-knowhow-list container\"\n");
      out.write("	data-v-0b8ae29e=\"\" data-v-2590092d=\"\">\n");
      out.write("	<section class=\"header short-bottom\" data-v-0b8ae29e=\"\">\n");
      out.write("	<h2 class=\"title\" data-v-0b8ae29e=\"\">이용자 게시판 목록</h2>\n");
      out.write("	<a href=\"/community/soomgo-life/\" data-testid=\"community-home\"\n");
      out.write("		class=\"go-list\" data-v-1b5b0368=\"\" data-v-0b8ae29e=\"\"><span\n");
      out.write("		data-v-1b5b0368=\"\">전체보기</span><img\n");
      out.write("		src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiIgdmlld0JveD0iMCAwIDE2IDE2Ij4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPGc+CiAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgPGc+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZD0iTTAgMEgxNlYxNkgweiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTEwNTMuMDAwMDAwLCAtMjAyLjAwMDAwMCkgdHJhbnNsYXRlKDQ4NS4wMDAwMDAsIDE4OC4wMDAwMDApIHRyYW5zbGF0ZSg1NjguMDAwMDAwLCAxNC4wMDAwMDApIi8+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggc3Ryb2tlPSIjMDBDN0FFIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS13aWR0aD0iMS41IiBkPSJNMTEgMTNMNiA4IDExIDMiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDUzLjAwMDAwMCwgLTIwMi4wMDAwMDApIHRyYW5zbGF0ZSg0ODUuMDAwMDAwLCAxODguMDAwMDAwKSB0cmFuc2xhdGUoNTY4LjAwMDAwMCwgMTQuMDAwMDAwKSB0cmFuc2xhdGUoOC41MDAwMDAsIDguMDAwMDAwKSBzY2FsZSgtMSwgMSkgdHJhbnNsYXRlKC04LjUwMDAwMCwgLTguMDAwMDAwKSIvPgogICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4K\"\n");
      out.write("		data-v-1b5b0368=\"\"></a></section>\n");
      out.write("	<div data-v-292a6694=\"\" data-v-0b8ae29e=\"\"\n");
      out.write("		class=\"main-community-contents\">\n");
      out.write("		<div data-v-292a6694=\"\" class=\"desktop-section\">\n");
      out.write("			<div data-v-292a6694=\"\" class=\"curation-container half-list\">\n");
      out.write("				<ul data-v-151ddbec=\"\" data-v-292a6694=\"\"\n");
      out.write("					data-testid=\"curation-list\" class=\"curation-list\">\n");
      out.write("					\n");
      out.write("					\n");
      out.write("					<li data-v-151ddbec=\"\" data-testid=\"curation-item\"\n");
      out.write("						class=\"curation-list-item\"><a data-v-151ddbec=\"\"\n");
      out.write("						href=\"/community/soomgo-life/posts/643d30b9f22d78d3e3cce686-%EC%88%98%ED%95%99%EA%B3%BC%EC%99%B8-%EC%9E%98-%EA%B5%AC%ED%95%98%EB%8A%94-%ED%8C%81\"\n");
      out.write("						class=\"curation-list-wrapper\"><div data-v-151ddbec=\"\"\n");
      out.write("								class=\"curation-contents has-thumbnail\">\n");
      out.write("								<p data-v-151ddbec=\"\" class=\"topic-name\">고수소식</p>\n");
      out.write("								<p data-v-151ddbec=\"\" class=\"curation-title\">수학과외 잘\n");
      out.write("									구하는 팁</p>\n");
      out.write("								<p data-v-151ddbec=\"\" class=\"curation-content\">선생님\n");
      out.write("									경력사항과 커리큘럼의 세부사항 확인하기! 자신에게 맞는 커리큘럼을 찾는다면 과외의 시너지가\n");
      out.write("									발휘됩니다.</p>\n");
      out.write("								<div data-v-151ddbec=\"\" class=\"curation-reactions\">\n");
      out.write("									<span data-v-151ddbec=\"\" class=\"view-count\">283</span><span\n");
      out.write("										data-v-151ddbec=\"\" class=\"comment-count\">9</span>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							</div></a>\n");
      out.write("						</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			<div data-v-292a6694=\"\" class=\"knowhow-container half-list\">\n");
      out.write("				<a data-v-292a6694=\"\"\n");
      out.write("					href=\"/community/pro-knowhow/754-%EC%9D%B4%EC%A7%81-%EB%A9%B4%EC%A0%91-%EC%9D%B4%EA%B1%B0-%EB%86%93%EC%B9%98%EB%A9%B4-%EB%B6%88%ED%95%A9%EA%B2%A9-\"\n");
      out.write("					class=\"knowhow-card-slide\" data-testid=\"knowhow-item\"><img\n");
      out.write("					data-v-292a6694=\"\" alt=\"이직 면접 이거 놓치면 불합격!\"\n");
      out.write("					class=\"thumb-image\"\n");
      out.write("					data-src=\"https://static.cdn.soomgo.com/upload/talkboard/daa7675e-e26d-4a0e-ac1f-ad53dc98a46a.png?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("					src=\"https://static.cdn.soomgo.com/upload/talkboard/daa7675e-e26d-4a0e-ac1f-ad53dc98a46a.png?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("					lazy=\"loaded\">\n");
      out.write("				<div data-v-292a6694=\"\" class=\"card-desc\">\n");
      out.write("						<p data-v-292a6694=\"\" class=\"service\">면접 컨설팅</p>\n");
      out.write("						<div data-v-a3afae98=\"\" data-v-292a6694=\"\"\n");
      out.write("							class=\"collapsed\">\n");
      out.write("							<div data-v-a3afae98=\"\" class=\"line-clamp\"\n");
      out.write("								style=\"line-height: 1.5; max-height: 3rem; -webkit-line-clamp: 2;\">\n");
      out.write("								<p data-v-292a6694=\"\" data-v-a3afae98=\"\" class=\"title\">이직\n");
      out.write("									면접 이거 놓치면 불합격!</p>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("						<p data-v-292a6694=\"\" class=\"author\">김주호</p>\n");
      out.write("					</div></a><a data-v-292a6694=\"\"\n");
      out.write("					href=\"/community/pro-knowhow/753-%EA%B3%B0%ED%8C%A1%EC%9D%B4-%EC%A0%9C%EA%B1%B0--%EA%B4%91%EA%B3%A0%EC%B2%98%EB%9F%BC-%EC%85%80%ED%94%84%EB%A1%9C-%EA%B0%80%EB%8A%A5%ED%95%A0%EA%B9%8C-\"\n");
      out.write("					class=\"knowhow-card-slide\" data-testid=\"knowhow-item\"><img\n");
      out.write("					data-v-292a6694=\"\" alt=\"곰팡이 제거, 광고처럼 셀프로 가능할까?\"\n");
      out.write("					class=\"thumb-image\"\n");
      out.write("					data-src=\"https://static.cdn.soomgo.com/upload/talkboard/8a64d04d-c5c6-4cc3-96af-2f1b8875f32a.jpg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("					src=\"https://static.cdn.soomgo.com/upload/talkboard/8a64d04d-c5c6-4cc3-96af-2f1b8875f32a.jpg?h=320&amp;w=480&amp;webp=1\"\n");
      out.write("					lazy=\"loaded\">\n");
      out.write("				<div data-v-292a6694=\"\" class=\"card-desc\">\n");
      out.write("						<p data-v-292a6694=\"\" class=\"service\">곰팡이 제거</p>\n");
      out.write("						<div data-v-a3afae98=\"\" data-v-292a6694=\"\"\n");
      out.write("							class=\"collapsed\">\n");
      out.write("							<div data-v-a3afae98=\"\" class=\"line-clamp\"\n");
      out.write("								style=\"line-height: 1.5; max-height: 3rem; -webkit-line-clamp: 2;\">\n");
      out.write("								<p data-v-292a6694=\"\" data-v-a3afae98=\"\" class=\"title\">곰팡이\n");
      out.write("									제거, 광고처럼 셀프로 가능할까?</p>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("						<p data-v-292a6694=\"\" class=\"author\">도배르만(곰팡이, 단열 전문)</p>\n");
      out.write("					</div></a>\n");
      out.write("			</div>																				\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div> --><!-- 이용자 게시글 닫는태그 --> ");
      out.write(" <!--인기있는 주니어 베너 끝-->\n");
      out.write("					\n");
      out.write("					\n");
      out.write("					<!-- recommend로 해야되는데 작성된게 없슴 -->\n");
      out.write("					 <!-- 주니어 들어오는곳 --> \n");
      out.write("					 <!-- <section id=\"content-wrap-js\">\n");
      out.write("							<ul style=\"text-align: center;\">\n");
      out.write("							</ul>\n");
      out.write("					</section>  -->\n");
      out.write("					\n");
      out.write("					\n");
      out.write("					<!-- 분야 -->\n");
      out.write("			<div data-v-a9f85b62=\"\" data-v-38e68602=\"\"\n");
      out.write("				class=\"main-pro-locations container no-mobile-padding\">\n");
      out.write("				<div data-v-a9f85b62=\"\" class=\"header\">\n");
      out.write("					<h2 data-v-a9f85b62=\"\" class=\"title\">분야</h2>\n");
      out.write("					<div data-v-a9f85b62=\"\" class=\"desc\">\n");
      out.write("						믿을 수 있는 전문가를<br data-v-a9f85b62=\"\" class=\"d-none d-sm-block\">\n");
      out.write("						중신 단 한 곳에서 찾으세요\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<ul data-v-a9f85b62=\"\" class=\"location-list\">\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EC%84%9C%EC%9A%B8\" class=\"\">음악</a></li>\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EC%84%B8%EC%A2%85\" class=\"\">미술</a></li>\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EA%B0%95%EC%9B%90\" class=\"\">입시</a></li>\n");
      out.write("\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EB%8C%80%EA%B5%AC\" class=\"\">건강</a></li>\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EC%A0%84%EB%B6%81\" class=\"\">미용</a></li>\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EA%B2%BD%EB%82%A8\" class=\"\">알바</a></li>\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EC%9A%B8%EC%82%B0\" class=\"\">개발</a></li>\n");
      out.write("					<li data-v-a9f85b62=\"\" class=\"location-item\"><a\n");
      out.write("						data-v-a9f85b62=\"\" href=\"/a.%EA%B4%91%EC%A3%BC\" class=\"\">기타</a></li>\n");
      out.write("\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<!-- 분야 --> <!-- 전문가로 활동하시나요? 주니어 가입 -->\n");
      out.write("			<div data-v-322fbd30=\"\" data-v-38e68602=\"\"\n");
      out.write("				class=\"main-pro-info container no-mobile-margin\">\n");
      out.write("				<div data-v-322fbd30=\"\" class=\"header\">\n");
      out.write("					<p data-v-322fbd30=\"\" class=\"title\">\n");
      out.write("						전문가로 활동하시나요?<br data-v-322fbd30=\"\"> 중신에서 새로운 고객을 <br\n");
      out.write("							data-v-322fbd30=\"\" class=\"d-none d-sm-block\">만나보세요\n");
      out.write("					</p>\n");
      out.write("					<div data-v-322fbd30=\"\" class=\"pro-signup-btn\">\n");
      out.write("						<a data-v-322fbd30=\"\" href=\"/pro\" class=\"btn btn-primary\"\n");
      out.write("							target=\"_self\">고수가입</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div data-v-3d1a4f76=\"\" data-v-55917fe8=\"\" data-v-322fbd30=\"\"\n");
      out.write("					dir=\"ltr\" class=\"slick-slider slick-initialized\">\n");
      out.write("					<button data-v-21137603=\"\" data-v-3d1a4f76=\"\" type=\"button\"\n");
      out.write("						data-role=\"none\" class=\"slick-arrow slick-prev\"\n");
      out.write("						style=\"display: block;\">Previous</button>\n");
      out.write("					<div data-v-3d1a4f76=\"\" class=\"slick-list\">\n");
      out.write("						<div data-v-e4caeaf8=\"\" data-v-3d1a4f76=\"\" class=\"slick-track\"\n");
      out.write("							style=\"width: 1923px; opacity: 1; transform: translate3d(-1282px, 0px, 0px);\">\n");
      out.write("							<div data-v-e4caeaf8=\"\" tabindex=\"-1\" data-index=\"0\"\n");
      out.write("								aria-hidden=\"true\" class=\"slick-slide\"\n");
      out.write("								style=\"outline: none; width: 641px;\">\n");
      out.write("								<div data-v-e4caeaf8=\"\">\n");
      out.write("									<div data-v-322fbd30=\"\" data-v-e4caeaf8=\"\" tabindex=\"-1\"\n");
      out.write("										style=\"width: 100%; display: inline-block;\">\n");
      out.write("										<div data-v-322fbd30=\"\" data-v-e4caeaf8=\"\"\n");
      out.write("											class=\"pro-info-slide\">\n");
      out.write("											<img data-v-322fbd30=\"\" data-v-e4caeaf8=\"\"\n");
      out.write("												src=\"https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-1.png\"\n");
      out.write("												srcset=\"https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-1.png 1x, https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-1@2x.png 2x, https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-1@3x.png 3x\"\n");
      out.write("												alt=\"고객의 요청서를 무료로 받으세요\" class=\"image\">\n");
      out.write("											<p data-v-322fbd30=\"\" data-v-e4caeaf8=\"\" class=\"desc\">고객의\n");
      out.write("												요청서를 무료로 받으세요</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div data-v-e4caeaf8=\"\" tabindex=\"-1\" data-index=\"1\"\n");
      out.write("								aria-hidden=\"true\" class=\"slick-slide\"\n");
      out.write("								style=\"outline: none; width: 641px;\">\n");
      out.write("								<div data-v-e4caeaf8=\"\">\n");
      out.write("									<div data-v-322fbd30=\"\" data-v-e4caeaf8=\"\" tabindex=\"-1\"\n");
      out.write("										style=\"width: 100%; display: inline-block;\">\n");
      out.write("										<div data-v-322fbd30=\"\" data-v-e4caeaf8=\"\"\n");
      out.write("											class=\"pro-info-slide\">\n");
      out.write("											<img data-v-322fbd30=\"\" data-v-e4caeaf8=\"\"\n");
      out.write("												src=\"https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-2.png\"\n");
      out.write("												srcset=\"https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-2.png 1x, https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-2@2x.png 2x, https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-2@3x.png 3x\"\n");
      out.write("												alt=\"조건이 맞는 고객에게 견적을 보내세요\" class=\"image\">\n");
      out.write("											<p data-v-322fbd30=\"\" data-v-e4caeaf8=\"\" class=\"desc\">조건이\n");
      out.write("												맞는 고객에게 견적을 보내세요</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div data-v-e4caeaf8=\"\" tabindex=\"-1\" data-index=\"2\"\n");
      out.write("								aria-hidden=\"false\"\n");
      out.write("								class=\"slick-slide slick-active slick-current\"\n");
      out.write("								style=\"outline: none; width: 641px;\">\n");
      out.write("								<div data-v-e4caeaf8=\"\">\n");
      out.write("									<div data-v-322fbd30=\"\" data-v-e4caeaf8=\"\" tabindex=\"-1\"\n");
      out.write("										style=\"width: 100%; display: inline-block;\">\n");
      out.write("										<div data-v-322fbd30=\"\" data-v-e4caeaf8=\"\"\n");
      out.write("											class=\"pro-info-slide\">\n");
      out.write("											<img data-v-322fbd30=\"\" data-v-e4caeaf8=\"\"\n");
      out.write("												src=\"https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-3.png\"\n");
      out.write("												srcset=\"https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-3.png 1x, https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-3@2x.png 2x, https://assets.cdn.soomgo.com/images/home/img-main-signup-pro-step-3@3x.png 3x\"\n");
      out.write("												alt=\"채팅, 전화로 빠르게 상담하고 거래하세요\" class=\"image\">\n");
      out.write("											<p data-v-322fbd30=\"\" data-v-e4caeaf8=\"\" class=\"desc\">채팅,\n");
      out.write("												전화로 빠르게 상담하고 거래하세요</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- 전문가로 활동하시나요? 주니어 가입 끝-->\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../static/css/mainpageSeo/hf.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<footer>\n");
      out.write("			<nav id=\"app-footer\" class=\"footer-container\" data-v-4e4965bd=\"\">\n");
      out.write("				<div class=\"footer-container-row container\" data-v-4e4965bd=\"\">\n");
      out.write("					<div class=\"col-content margin-bottom\" data-v-4e4965bd=\"\">\n");
      out.write("						<p class=\"text contact\" data-v-4e4965bd=\"\">1599-5319</p>\n");
      out.write("						<p class=\"text-middle\" data-v-4e4965bd=\"\">\n");
      out.write("							평일 10:00 - 18:00<br data-v-4e4965bd=\"\">(점심시간 13:00 - 14:00\n");
      out.write("							제외 · 주말/공휴일 제외)\n");
      out.write("						</p>\n");
      out.write("						<a class=\"download\" data-v-4e4965bd=\"\"\n");
      out.write("							href=\"https://soomgoapp.onelink.me/6cqv?af_channel=cpc&amp;af_dp=smgo%3A%2F%2Fhome%2F&amp;af_keywords=%EC%88%A8%EA%B3%A0&amp;af_sub2=%EB%A9%94%EC%9D%B8&amp;af_sub4=footer&amp;af_web_dp=https%3A%2F%2Fsoomgo.com%2Fapp-download%2Fsender&amp;c=%EB%A9%94%EC%9D%B8&amp;pid=google\"><img\n");
      out.write("							src=\"https://assets.cdn.soomgo.com/icons/icon-download-appstore.svg\"\n");
      out.write("							alt=\"앱스토어\" data-v-4e4965bd=\"\">APP STORE </a><a class=\"download\"\n");
      out.write("							data-v-4e4965bd=\"\"\n");
      out.write("							href=\"https://soomgoapp.onelink.me/6cqv?af_channel=cpc&amp;af_dp=smgo%3A%2F%2Fhome%2F&amp;af_keywords=%EC%88%A8%EA%B3%A0&amp;af_sub2=%EB%A9%94%EC%9D%B8&amp;af_sub4=footer&amp;af_web_dp=https%3A%2F%2Fsoomgo.com%2Fapp-download%2Fsender&amp;c=%EB%A9%94%EC%9D%B8&amp;pid=google\"><img\n");
      out.write("							src=\"https://assets.cdn.soomgo.com/icons/icon-download-palystore.svg\"\n");
      out.write("							alt=\"구글플레이\" data-v-4e4965bd=\"\">PLAY STORE </a>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-content right\" data-v-4e4965bd=\"\">\n");
      out.write("						<ul class=\"content-list\" data-v-4e4965bd=\"\">\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									중신소개 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/about\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 회사소개 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://soomgo.career.greetinghr.com/\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 채용안내 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://blog.soomgo.com\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 팀블로그 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\n");
      out.write("								</div></li>\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									고객안내 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/how-it-works\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 이용안내 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/safety\" class=\"text-middle category\" data-v-4e4965bd=\"\">\n");
      out.write("										안전정책 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\n");
      out.write("									</a><a href=\"/prices\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 예상금액 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/search/pro?from=footer\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어찾기 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/articles/360056329911\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 주니어보증 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/questions/\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어에게묻다 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/community/soomgo-life/all\"\n");
      out.write("										class=\"text-middle category sr-only\" data-v-4e4965bd=\"\">\n");
      out.write("										커뮤니티 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\n");
      out.write("									</a>\n");
      out.write("								</div></li>\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									주니어안내 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/how-soomgo-works\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 이용안내 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/categories/115001218027\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 주니어가이드 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/pro\" class=\"text-middle category\" data-v-4e4965bd=\"\">\n");
      out.write("										주니어가입 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\n");
      out.write("									</a><a href=\"/pro-center\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어센터 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\n");
      out.write("								</div></li>\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									고객센터 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/categories/360002081551-%EA%B3%B5%EC%A7%80%EC%82%AC%ED%95%AD\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 공지사항 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 자주묻는질문 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\n");
      out.write("								</div></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"footer-container-row container terms\" data-v-4e4965bd=\"\">\n");
      out.write("					<div class=\"term-container\" data-v-4e4965bd=\"\">\n");
      out.write("						<div class=\"col-content term-content\" data-v-4e4965bd=\"\">\n");
      out.write("							<div class=\"col-content-list-term\" data-v-4e4965bd=\"\">\n");
      out.write("								<div class=\"terms-group\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/terms/usage\" class=\"text term\" data-v-4e4965bd=\"\">이용약관</a><a\n");
      out.write("										href=\"/terms/privacy\" class=\"text term\" data-v-4e4965bd=\"\">개인정보처리방침</a>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"terms-group\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/terms/location\" class=\"text term\" data-v-4e4965bd=\"\">위치기반\n");
      out.write("										서비스 이용약관</a><a target=\"_blank\" rel=\"nofollow\"\n");
      out.write("										href=\"https://www.ftc.go.kr/bizCommPop.do?wrkr_no=1208822325\"\n");
      out.write("										class=\"text term\" data-v-4e4965bd=\"\"> 사업자 정보확인 </a>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-content-list-term\" data-v-4e4965bd=\"\">\n");
      out.write("								<span class=\"text term-text\" data-v-4e4965bd=\"\">\n");
      out.write("									(주)브레이브모바일은 통신판매중개자로서 통신판매의 당사자가 아니며 개별 판매자가 제공하는 서비스에 대한 이행,\n");
      out.write("									계약사항 등과 관련한 의무와 책임은 거래당사자에게 있습니다. </span>\n");
      out.write("							</div>\n");
      out.write("							<ul class=\"col-content-guide\" data-v-4e4965bd=\"\">\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">상호명:(주)브레이브모바일 ·\n");
      out.write("									대표이사:KIM ROBIN H · 개인정보책임관리자:김태우 · 주소:서울특별시 강남구 테헤란로 415, L7\n");
      out.write("									강남타워 5층</li>\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">사업자등록번호:120-88-22325 ·\n");
      out.write("									통신판매업신고증:제 2021-서울강남-00551 호 · 직업정보제공사업 신고번호:서울청 제 2019-21호</li>\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">고객센터:1599-5319 ·\n");
      out.write("									이메일:support@soomgo.com</li>\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">Copyright ©Brave Mobile\n");
      out.write("									Inc. All Rights Reserved.</li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"col-content badge-list right\" data-v-4e4965bd=\"\">\n");
      out.write("							<a href=\"https://www.facebook.com/SoomgoKorea/\" target=\"_blank\"\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-facebook.svg\"\n");
      out.write("								alt=\"주니어 페이스북 계정\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://www.instagram.com/soomgo_official/\"\n");
      out.write("								target=\"_blank\" class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-instagram.svg\"\n");
      out.write("								alt=\"주니어 인스타그램\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://blog.naver.com/brave_mobile_mkt/\" target=\"_blank\"\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-naverblog.svg\"\n");
      out.write("								alt=\"주니어 블로그\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://post.naver.com/brave_mobile_mkt?isHome=1\"\n");
      out.write("								target=\"_blank\" class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-naverpost.svg\"\n");
      out.write("								alt=\"주니어 포스트\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://news.soomgo.com\" target=\"_blank\"\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-tistory.svg\"\n");
      out.write("								alt=\"주니어 스토리\" data-v-4e4965bd=\"\"></a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("	</div>\n");
      out.write("	<!-- 전체 div -->\n");
      out.write("	</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/mainpageSeo/board.js\"></script>\n");
      out.write("<script>\n");
      out.write("	let boards = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boards}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\n");
      out.write("	boards = boards.replace(/\\n/g, \"\");\n");
      out.write("	/* let boardsJunior = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardsJunior}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`; */\n");
      out.write("	let contextPath = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\n");
      out.write("\n");
      out.write("	let $form = $(\"form[name='page-form']\");\n");
      out.write("	$(\"a.change-page\").on(\"click\", function(e) {\n");
      out.write("		e.preventDefault();\n");
      out.write("		$form.find(\"input[name='page']\").val($(this).attr(\"href\"));\n");
      out.write("		$form.submit();\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<script\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/mainpageSeo/list.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"/static/js/mainpageSeo/main-page.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /templates/mainpageSeo/main-page.jsp(46,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.userId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../mainpageSeo/loginHeader.jsp", out, false);
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../mainpageSeo/header.jsp", out, false);
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
