/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 06:59:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.request_002dboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class request_002dboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/templates/request-board/../mainpageSeo/header.jsp", Long.valueOf(1683040932032L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1681825652000L));
    _jspx_dependants.put("jar:file:/Users/gimjin/Desktop/web_1900_hds/jsp/workspace/joongshin/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/templates/request-board/../mainpageSeo/footer.jsp", Long.valueOf(1682517413499L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/request-board-jym/request-board.css\">\n");
      out.write("<link\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/logo/logo.png\"\n");
      out.write("	rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/mainpageSeo/hf.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/mainpageSeo/hf.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<title>숨고</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<form action=\"\">\n");
      out.write("		<div id=\"app\" class=\"webp\" data-is-loaded=\"true\">\n");
      out.write("			");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- 로고 -->\n");
      out.write("<link href=\"../../static/image/logo/logo.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../static/css/mainpageSeo/hf.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"home\">\n");
      out.write("<div class=\"h__cov-progress\" style=\"background-color: rgb(0, 199, 174); opacity: 0; position: fixed; top: 0px; left: 0px; width: 0%; height: 2px; transition: opacity 0.6s ease 0s;\"></div>\n");
      out.write("		<header id=\"app-header\" class=\"h_global-header\" data-v-50506024=\"\">\n");
      out.write("			<div data-v-5f10666f=\"\" data-v-50506024=\"\"\n");
      out.write("				class=\"h-global-navigation-bar\">\n");
      out.write("				<!-- 섹션태그때문에 이미지가 나오지 않아서 없애버렸어요 -->\n");
      out.write("				<div data-v-5f10666f=\"\" class=\"h-desktop-header\">\n");
      out.write("					<div data-v-5f10666f=\"\" class=\"left-section\" style=\"margin-right: 250px\">\n");
      out.write("						<div data-v-5f10666f=\"\" class=\"logo\">\n");
      out.write("							<a data-v-5f10666f=\"\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listOk.board\" class=\"\"> <img\n");
      out.write("								data-v-5f10666f=\"\"\n");
      out.write("								src=\"../../static/image/logo/JOONGSHIN.svg\"\n");
      out.write("								alt=\"숨고, 숨은고수\">\n");
      out.write("							</a>\n");
      out.write("						</div>\n");
      out.write("						<nav data-v-5f10666f=\"\">\n");
      out.write("							<ul data-v-5f10666f=\"\" class=\"nav-list\">\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item left-section-item\"><a\n");
      out.write("									data-v-5f10666f=\"\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/comulistOk.board\">\n");
      out.write("									<span data-v-5f10666f=\"\">커뮤니티</span></a></li>\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item left-section-item\"><a\n");
      out.write("									data-v-5f10666f=\"\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reqBoard.board\">\n");
      out.write("									<span data-v-5f10666f=\"\">문의 게시판</span></a></li>\n");
      out.write("						\n");
      out.write("							</ul>\n");
      out.write("						</nav>\n");
      out.write("					</div>\n");
      out.write("					<!--  					 로고,문자열 네개까지 ↑ -->\n");
      out.write("					");
      out.write("\n");
      out.write("					<!-- 로그인 회원가입 고수가입 전↑ -->\n");
      out.write("					<div data-v-5f10666f=\"\" class=\"right-section\">\n");
      out.write("						<nav data-v-5f10666f=\"\">\n");
      out.write("							<ul data-v-5f10666f=\"\" class=\"nav-list\">\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item right-section-item\" style=\"margin-right: 40px;\"><a\n");
      out.write("									data-v-5f10666f=\"\" href=\"/login.user\" class=\"gnb-link\"><span\n");
      out.write("										data-v-5f10666f=\"\">로그인</span></a> <!----></li>\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item right-section-item\" style=\"margin-right: 40px;\"><a\n");
      out.write("									href=\"/join.user\"\n");
      out.write("									class=\"gnb-link\"><span data-v-5f10666f=\"\">회원가입</span></a> <!----></li>\n");
      out.write("							</ul>\n");
      out.write("						</nav>\n");
      out.write("						<button data-v-5f10666f=\"\" type=\"button\"\n");
      out.write("							class=\"h-btn pro-signup-h-btn right-section-item h-btn-primary h-btn-primary2\">\n");
      out.write("							<a data-v-5f10666f=\"\" href=\"/gosuLogin.juniorUser\" class=\"\">주니어 가입</a>\n");
      out.write("						</button>\n");
      out.write("						<!---->\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<!-- 헤더 전체 div 닫는부분 -->\n");
      out.write("				<!-- 없애버린 세션 태그 닫는자리 -->\n");
      out.write("			</div>\n");
      out.write("		</header>\n");
      out.write("		<!-- 헤더 끝 -->\n");
      out.write("		</div>\n");
      out.write("		</body>\n");
      out.write("</html>\n");
      out.write("		\n");
      out.write("		");
      out.write("\n");
      out.write("			<!-- 헤더 부분 -->\n");
      out.write("			<!-- 바디 -->\n");
      out.write("			<div id=\"app-body\">\n");
      out.write("				<div id=\"container\">\n");
      out.write("					<div id=\"joongshin-container\">\n");
      out.write("						<section id=\"questions\" class=\"questions\">\n");
      out.write("\n");
      out.write("							<!-- 바디 페이지 헤더 부분 -->\n");
      out.write("							<!-- 본문 리스트 -->\n");
      out.write("							<div class=\"questions-content-layout\">\n");
      out.write("								<!-- 문의 게시판 내부 검색창 -->\n");
      out.write("								<!-- <div class=\"search-questions d-none\">\n");
      out.write("									<form class=\"search-form\">\n");
      out.write("										 <div role=\"group\" class=\"input-group\">\n");
      out.write("											<div class=\"input-group-prepend\">\n");
      out.write("												<img\n");
      out.write("													src=\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgiIGhlaWdodD0iMTgiIHZpZXdCb3g9IjAgMCAxOCAxOCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEgMSkiIHN0cm9rZT0iI0M1QzVDNSIgc3Ryb2tlLXdpZHRoPSIxLjUiIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPGNpcmNsZSBjeD0iNi42MTEiIGN5PSI2LjYxMSIgcj0iNS44NjEiLz4KICAgICAgICA8cGF0aCBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGQ9Im0xNS4yNSAxNS4yNS00LjI0My00LjI0MyIvPgogICAgPC9nPgo8L3N2Zz4K\"\n");
      out.write("													alt=\"커뮤니티 검색 아이콘\" class=\"search\">\n");
      out.write("											</div>\n");
      out.write("											<input type=\"text\" placeholder=\"키워드와 #태그 모두 검색할 수 있어요.\"\n");
      out.write("												autocomplete=\"off\" class=\"search-input form-control\"\n");
      out.write("												maxlength=\"15\" id=\"__BVID__4795\" name=\"searchKeyword\">  \n");
      out.write("											<div class=\"input-group-append\">\n");
      out.write("												<img\n");
      out.write("													src=\"data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZD0iTTAgMGgyNHYyNEgweiIvPgogICAgICAgIDxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDMgMykiPgogICAgICAgICAgICA8Y2lyY2xlIGZpbGw9IiNDNUM1QzUiIGN4PSI5IiBjeT0iOSIgcj0iOSIvPgogICAgICAgICAgICA8cGF0aCBzdHJva2U9IiNGRkYiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGQ9Im02IDYgNi4wMDUgNi4wMDZNMTIuMDA1IDYgNiAxMi4wMDYiLz4KICAgICAgICA8L2c+CiAgICA8L2c+Cjwvc3ZnPgo=\"\n");
      out.write("													alt=\"검색어 삭제 아이콘\" class=\"reset\" style=\"display: none;\">\n");
      out.write("											</div>\n");
      out.write("										</div>  \n");
      out.write("									</form>\n");
      out.write("								</div> -->\n");
      out.write("								<!-- 베너 '지금 가장 뜨거운 숨고픽' -->\n");
      out.write("								<!-- <section class=\"curation\">\n");
      out.write("									<div class=\"curation-header\">\n");
      out.write("										<h2 class=\"sg-text-headline sg-font-bold sg-text-gray-900\">지금\n");
      out.write("											가장 뜨거운 숨고픽🔥</h2>\n");
      out.write("										<span class=\"curation-page\">1/2</span>\n");
      out.write("									</div>\n");
      out.write("									배너\n");
      out.write("									<div class=\"slick-slider\">\n");
      out.write("										<button type=\"button\" data-role=\"none\"\n");
      out.write("											class=\"slick-arrow slick-prev slick-disabled\"\n");
      out.write("											style=\"display: block;\">Previous</button>\n");
      out.write("										<div class=\"slick-list\">\n");
      out.write("											<div class=\"slick-track\"\n");
      out.write("												style=\"width: 1020px; opacity: 1; transform: translate3d(0px, 0px, 0px);\">\n");
      out.write("												<div tabindex=\"-1\" data-index=\"0\"\n");
      out.write("													class=\"slick-slide slick-active slick-current\"\n");
      out.write("													style=\"outline: none; width: 204px;\">\n");
      out.write("													<div>\n");
      out.write("														<a\n");
      out.write("															href=\"/community/soomgo-life/posts/63db8b3ad1becfebc58891bc-%EC%88%A8%EA%B3%A0%EC%83%9D%ED%99%9C-%EA%B0%80%EC%9D%B4%EB%93%9C%EB%9D%BC%EC%9D%B8---?from=curation\"\n");
      out.write("															class=\"\" data-testid=\"curation-item\" tabindex=\"-1\"\n");
      out.write("															style=\"width: 100%; display: inline-block;\">\n");
      out.write("															<div class=\"curation-item admin-post\">\n");
      out.write("																<p\n");
      out.write("																	class=\"topic sg-text-subhead7 sg-font-medium sg-text-gray-500\">\n");
      out.write("																	공지사항</p>\n");
      out.write("																<h3\n");
      out.write("																	class=\"sg-text-subhead2 sg-font-bold sg-text-gray-900\">\n");
      out.write("																	숨고생활 가이드라인 🤝</h3>\n");
      out.write("																<p\n");
      out.write("																	class=\"user-name sg-text-description sg-font-regular sg-text-white\">\n");
      out.write("																	Soomgo</p>\n");
      out.write("															</div>\n");
      out.write("														</a>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div tabindex=\"-1\" data-index=\"1\" aria-hidden=\"false\"\n");
      out.write("													class=\"slick-slide slick-active\"\n");
      out.write("													style=\"outline: none; width: 204px;\">\n");
      out.write("													<div>\n");
      out.write("														<a\n");
      out.write("															href=\"/community/soomgo-life/posts/641a7cbf3696545a889f3bc5-%EC%88%A8%EA%B3%A0-50%EB%A7%8C-%EC%BA%90%EC%8B%9C%EC%99%80-%EC%BF%A0%ED%8F%B0-%EB%B0%9B%EC%9C%BC%EC%84%B8%EC%9A%94--?from=curation\"\n");
      out.write("															class=\"\" data-testid=\"curation-item\" tabindex=\"-1\"\n");
      out.write("															style=\"width: 100%; display: inline-block;\">\n");
      out.write("															<div class=\"curation-item admin-post\">\n");
      out.write("																<p\n");
      out.write("																	class=\"topic sg-text-subhead7 sg-font-medium sg-text-gray-500\">\n");
      out.write("																	공지사항</p>\n");
      out.write("																<h3\n");
      out.write("																	class=\"sg-text-subhead2 sg-font-bold sg-text-gray-900\">\n");
      out.write("																	숨고 50만 캐시와 쿠폰 받으세요🎁</h3>\n");
      out.write("																<p\n");
      out.write("																	class=\"user-name sg-text-description sg-font-regular sg-text-white\">\n");
      out.write("																	Soomgo</p>\n");
      out.write("															</div>\n");
      out.write("														</a>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div tabindex=\"-1\" data-index=\"2\" aria-hidden=\"false\"\n");
      out.write("													class=\"slick-slide slick-active\"\n");
      out.write("													style=\"outline: none; width: 204px;\">\n");
      out.write("													<div>\n");
      out.write("														<a\n");
      out.write("															href=\"/community/soomgo-life/posts/643384c0505cb9f47887cdc0---%EC%88%A8%EA%B3%A0-%EC%9D%B8%ED%84%B0%EB%B7%B0-%EC%A3%BC%EC%9D%B8%EA%B3%B5%EC%9D%B4-%EB%90%98%EC%96%B4%EB%B3%B4%EC%84%B8%EC%9A%94-?from=curation\"\n");
      out.write("															class=\"\" data-testid=\"curation-item\" tabindex=\"-1\"\n");
      out.write("															style=\"width: 100%; display: inline-block;\">\n");
      out.write("															<div class=\"curation-item admin-post\">\n");
      out.write("																<p\n");
      out.write("																	class=\"topic sg-text-subhead7 sg-font-medium sg-text-gray-500\">\n");
      out.write("																	공지사항</p>\n");
      out.write("																<h3\n");
      out.write("																	class=\"sg-text-subhead2 sg-font-bold sg-text-gray-900\">\n");
      out.write("																	💌숨고 인터뷰 주인공이 되어보세요!</h3>\n");
      out.write("																<p\n");
      out.write("																	class=\"user-name sg-text-description sg-font-regular sg-text-white\">\n");
      out.write("																	Soomgo</p>\n");
      out.write("															</div>\n");
      out.write("														</a>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div tabindex=\"-1\" data-index=\"3\" aria-hidden=\"true\"\n");
      out.write("													class=\"slick-slide\" style=\"outline: none; width: 204px;\">\n");
      out.write("													<div>\n");
      out.write("														<a\n");
      out.write("															href=\"/community/soomgo-life/posts/643982c1a982a333f790f526-%EC%9A%B4%EC%A0%84%EC%97%B0%EC%88%98-%EA%B3%A0%EC%88%98%EB%8B%98-%EC%B0%BE%EC%95%84%EC%9A%94--?from=curation\"\n");
      out.write("															class=\"\" data-testid=\"curation-item\" tabindex=\"-1\"\n");
      out.write("															style=\"width: 100%; display: inline-block;\">\n");
      out.write("															<div class=\"curation-item\">\n");
      out.write("																<p\n");
      out.write("																	class=\"topic sg-text-subhead7 sg-font-medium sg-text-gray-500\">\n");
      out.write("																	고수찾아요</p>\n");
      out.write("																<h3\n");
      out.write("																	class=\"sg-text-subhead2 sg-font-bold sg-text-gray-900\">\n");
      out.write("																	운전연수 고수님 찾아요😊</h3>\n");
      out.write("																<div class=\"react-items\">\n");
      out.write("																	<p\n");
      out.write("																		class=\"view sg-text-description sg-font-regular sg-text-gray-300\">\n");
      out.write("																		297</p>\n");
      out.write("																	<p\n");
      out.write("																		class=\"comment sg-text-description sg-font-regular sg-text-gray-300\">\n");
      out.write("																		8</p>\n");
      out.write("																</div>\n");
      out.write("															</div>\n");
      out.write("														</a>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("												<div tabindex=\"-1\" data-index=\"4\" aria-hidden=\"true\"\n");
      out.write("													class=\"slick-slide\" style=\"outline: none; width: 204px;\">\n");
      out.write("													<div>\n");
      out.write("														<a\n");
      out.write("															href=\"/community/soomgo-life/posts/643a44cbf22d78d3e3cce226-%EC%88%A0-%EA%B0%90%EC%A0%95%EA%B0%80%EC%9D%98%EB%A2%B0?from=curation\"\n");
      out.write("															class=\"\" data-testid=\"curation-item\" tabindex=\"-1\"\n");
      out.write("															style=\"width: 100%; display: inline-block;\">\n");
      out.write("															<div class=\"curation-item\">\n");
      out.write("																<p\n");
      out.write("																	class=\"topic sg-text-subhead7 sg-font-medium sg-text-gray-500\">\n");
      out.write("																	얼마예요</p>\n");
      out.write("																<h3\n");
      out.write("																	class=\"sg-text-subhead2 sg-font-bold sg-text-gray-900\">\n");
      out.write("																	술 감정가의뢰</h3>\n");
      out.write("																<div class=\"react-items\">\n");
      out.write("																	<p\n");
      out.write("																		class=\"view sg-text-description sg-font-regular sg-text-gray-300\">\n");
      out.write("																		314</p>\n");
      out.write("																	<p\n");
      out.write("																		class=\"comment sg-text-description sg-font-regular sg-text-gray-300\">\n");
      out.write("																		17</p>\n");
      out.write("																</div>\n");
      out.write("															</div>\n");
      out.write("														</a>\n");
      out.write("													</div>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("										<button type=\"button\" data-role=\"none\"\n");
      out.write("											class=\"slick-arrow slick-next\" style=\"display: block;\">Next</button>\n");
      out.write("									</div>\n");
      out.write("								</section>\n");
      out.write(" -->\n");
      out.write("								<div class=\"observer-container\">\n");
      out.write("									<section class=\"questions-header\" id=\"questions-header\">\n");
      out.write("										<h1 class=\"questions-title\">문의 게시판</h1>\n");
      out.write("										<div>\n");
      out.write("											<div class=\"write-button-desktop\">\n");
      out.write("												<div class=\"dropdown b-dropdown btn-group\">\n");
      out.write("													<!---->\n");
      out.write("													<button type=\"button\"\n");
      out.write("														class=\"btn dropdown-toggle btn-primary\"\n");
      out.write("														style=\"cursor: pointer;\"\n");
      out.write("														onClick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reqWrite.board'\">글쓰기</button>\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("\n");
      out.write("									</section>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<!-- 서비스/지역 필터 -->\n");
      out.write("								<section class=\"service-area-filter all fixed\">\n");
      out.write("									<button type=\"button\" class=\"btn btn-none chip-btn filter-btn\">\n");
      out.write("										<a class=\"sort\"><span data-v-130d9011=\"\">내가 쓴 글</span></a>\n");
      out.write("									</button>\n");
      out.write("									<!-- 									<button type=\"button\" class=\"btn btn-none chip-btn filter-btn\"\n");
      out.write("										data-v-130d9011=\"\">\n");
      out.write("										<span data-v-130d9011=\"\">지역</span>\n");
      out.write("									</button>\n");
      out.write(" -->\n");
      out.write("								</section>\n");
      out.write("								<!-- 피드 (게시글 목록) -->\n");
      out.write("								<article class=\"questions-feed-list\">\n");
      out.write("									<ul class=\"feed-list\" id=\"content-wrap\">\n");
      out.write("										<!-- <li class=\"feed-item\">\n");
      out.write("												<a href=\"\" class=\"\" data-testid=\"soomgo-life-feed-item\">\n");
      out.write("														<p class=\"topic-name\">태그 들어갈 내용</p>\n");
      out.write("														<div class=\"feed-content service-address-info\">\n");
      out.write("															<div>\n");
      out.write("																<section class=\"item-wrapper\">\n");
      out.write("																	<h3>문의 글 제목</h3>\n");
      out.write("																	<p class=\"content\">본문 내용</p>\n");
      out.write("																</section>\n");
      out.write("																<p>지역정보</p>\n");
      out.write("															</div>\n");
      out.write("															<img alt=\"Resized_temp_1668128590947.1130780476_126927628503406.jpg\" data-src=\"https://static.cdn.soomgo.com/upload/media/aaa72ebc-fa5a-485c-9047-b364d82f4e33.jpg?h=80&amp;w=80&amp;webp=1\" src=\"https://static.cdn.soomgo.com/upload/media/aaa72ebc-fa5a-485c-9047-b364d82f4e33.jpg?h=80&amp;w=80&amp;webp=1\" lazy=\"loaded\">\n");
      out.write("															이미지 추가 할 내용\n");
      out.write("														</div>\n");
      out.write("														<div class=\"feed-footer\">\n");
      out.write("															<div class=\"user-interaction\">\n");
      out.write("																<span class=\"like sg-text-description sg-font-regular sg-text-gray-300\">추천 수</span>\n");
      out.write("																<span class=\"comment sg-text-description sg-font-regular sg-text-gray-300\">댓글 수</span>\n");
      out.write("															</div>\n");
      out.write("															<span class=\"sg-text-description sg-font-regular sg-text-gray-300\">작성 시간 ex) 00분전</span>\n");
      out.write("														</div>\n");
      out.write("													</a>\n");
      out.write("												</li> -->\n");
      out.write("									</ul>\n");
      out.write("								</article>\n");
      out.write("							</div>\n");
      out.write("					</div>\n");
      out.write("					<a id=\"top-btn\" role=\"button\" aria-label=\"위로 가기 버튼\" class=\"top-btn\"\n");
      out.write("						style=\"display: none;\"><img\n");
      out.write("						src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPGc+CiAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgPGc+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZD0iTTAgMEgyNFYyNEgweiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTMyMy4wMDAwMDAsIC02ODAuMDAwMDAwKSB0cmFuc2xhdGUoMzExLjAwMDAwMCwgNjY4LjAwMDAwMCkgdHJhbnNsYXRlKDEyLjAwMDAwMCwgMTIuMDAwMDAwKSIvPgogICAgICAgICAgICAgICAgICAgIDxnIHN0cm9rZT0iI0I1QjVCNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2Utd2lkdGg9IjEuNSI+CiAgICAgICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik03IDBMNyAxNSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTMyMy4wMDAwMDAsIC02ODAuMDAwMDAwKSB0cmFuc2xhdGUoMzExLjAwMDAwMCwgNjY4LjAwMDAwMCkgdHJhbnNsYXRlKDEyLjAwMDAwMCwgMTIuMDAwMDAwKSB0cmFuc2xhdGUoNS4wMDAwMDAsIDQuNTAwMDAwKSIvPgogICAgICAgICAgICAgICAgICAgICAgICA8cGF0aCBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNMCA3TDcgMCAxNCA3IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMzIzLjAwMDAwMCwgLTY4MC4wMDAwMDApIHRyYW5zbGF0ZSgzMTEuMDAwMDAwLCA2NjguMDAwMDAwKSB0cmFuc2xhdGUoMTIuMDAwMDAwLCAxMi4wMDAwMDApIHRyYW5zbGF0ZSg1LjAwMDAwMCwgNC41MDAwMDApIi8+CiAgICAgICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9nPgogICAgPC9nPgo8L3N2Zz4K\"\n");
      out.write("						alt=\"위로 가기\"></a>\n");
      out.write("					</section>\n");
      out.write("\n");
      out.write("					<!-- 글 상세보기에서 링크 이동할 부분 -->\n");
      out.write("					<div class=\"v-portal\" style=\"display: none;\"></div>\n");
      out.write("\n");
      out.write("					<div id=\"paging-wrap\">\n");
      out.write("                	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </div>\n");
      out.write("					\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"app-sticky\" class=\"portal-target\"></div>\n");
      out.write("		<div id=\"app-body\"></div>\n");
      out.write("		<nav id=\"app-footer\" class=\"footer-container\"></nav>\n");
      out.write("		<div class=\"portal-target\"></div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</form>\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../static/css/mainpageSeo/hf.css\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<footer>\n");
      out.write("			<nav id=\"app-footer\" class=\"footer-container\" data-v-4e4965bd=\"\">\n");
      out.write("				<div class=\"footer-container-row container\" data-v-4e4965bd=\"\">\n");
      out.write("					<div class=\"col-content margin-bottom\" data-v-4e4965bd=\"\">\n");
      out.write("						<p class=\"text contact\" data-v-4e4965bd=\"\">1599-5319</p>\n");
      out.write("						<p class=\"text-middle\" data-v-4e4965bd=\"\">\n");
      out.write("							평일 10:00 - 18:00<br data-v-4e4965bd=\"\">(점심시간 13:00 - 14:00\n");
      out.write("							제외 · 주말/공휴일 제외)\n");
      out.write("						</p>\n");
      out.write("						<a class=\"download\" data-v-4e4965bd=\"\"\n");
      out.write("							href=\"https://soomgoapp.onelink.me/6cqv?af_channel=cpc&amp;af_dp=smgo%3A%2F%2Fhome%2F&amp;af_keywords=%EC%88%A8%EA%B3%A0&amp;af_sub2=%EB%A9%94%EC%9D%B8&amp;af_sub4=footer&amp;af_web_dp=https%3A%2F%2Fsoomgo.com%2Fapp-download%2Fsender&amp;c=%EB%A9%94%EC%9D%B8&amp;pid=google\"><img\n");
      out.write("							src=\"https://assets.cdn.soomgo.com/icons/icon-download-appstore.svg\"\n");
      out.write("							alt=\"앱스토어\" data-v-4e4965bd=\"\">APP STORE </a><a class=\"download\"\n");
      out.write("							data-v-4e4965bd=\"\"\n");
      out.write("							href=\"https://soomgoapp.onelink.me/6cqv?af_channel=cpc&amp;af_dp=smgo%3A%2F%2Fhome%2F&amp;af_keywords=%EC%88%A8%EA%B3%A0&amp;af_sub2=%EB%A9%94%EC%9D%B8&amp;af_sub4=footer&amp;af_web_dp=https%3A%2F%2Fsoomgo.com%2Fapp-download%2Fsender&amp;c=%EB%A9%94%EC%9D%B8&amp;pid=google\"><img\n");
      out.write("							src=\"https://assets.cdn.soomgo.com/icons/icon-download-palystore.svg\"\n");
      out.write("							alt=\"구글플레이\" data-v-4e4965bd=\"\">PLAY STORE </a>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-content right\" data-v-4e4965bd=\"\">\n");
      out.write("						<ul class=\"content-list\" data-v-4e4965bd=\"\">\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									중신소개 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/about\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 회사소개 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://soomgo.career.greetinghr.com/\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 채용안내 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://blog.soomgo.com\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 팀블로그 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\n");
      out.write("								</div></li>\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									고객안내 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/how-it-works\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 이용안내 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/safety\" class=\"text-middle category\" data-v-4e4965bd=\"\">\n");
      out.write("										안전정책 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\n");
      out.write("									</a><a href=\"/prices\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 예상금액 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/search/pro?from=footer\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어찾기 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/articles/360056329911\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 주니어보증 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/questions/\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어에게묻다 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/community/soomgo-life/all\"\n");
      out.write("										class=\"text-middle category sr-only\" data-v-4e4965bd=\"\">\n");
      out.write("										커뮤니티 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\n");
      out.write("									</a>\n");
      out.write("								</div></li>\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									주니어안내 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/how-soomgo-works\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 이용안내 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/categories/115001218027\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 주니어가이드 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"/pro\" class=\"text-middle category\" data-v-4e4965bd=\"\">\n");
      out.write("										주니어가입 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\n");
      out.write("									</a><a href=\"/pro-center\" class=\"text-middle category\"\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어센터 <span class=\"new-badge\"\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\n");
      out.write("								</div></li>\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\n");
      out.write("									고객센터 <span class=\"new-badge\" style=\"display: none;\"\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\n");
      out.write("								<!---->\n");
      out.write("							</span>\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\n");
      out.write("									<a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/categories/360002081551-%EA%B3%B5%EC%A7%80%EC%82%AC%ED%95%AD\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 공지사항 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko\"\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 자주묻는질문 <span\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\n");
      out.write("								</div></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"footer-container-row container terms\" data-v-4e4965bd=\"\">\n");
      out.write("					<div class=\"term-container\" data-v-4e4965bd=\"\">\n");
      out.write("						<div class=\"col-content term-content\" data-v-4e4965bd=\"\">\n");
      out.write("							<div class=\"col-content-list-term\" data-v-4e4965bd=\"\">\n");
      out.write("								<div class=\"terms-group\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/terms/usage\" class=\"text term\" data-v-4e4965bd=\"\">이용약관</a><a\n");
      out.write("										href=\"/terms/privacy\" class=\"text term\" data-v-4e4965bd=\"\">개인정보처리방침</a>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"terms-group\" data-v-4e4965bd=\"\">\n");
      out.write("									<a href=\"/terms/location\" class=\"text term\" data-v-4e4965bd=\"\">위치기반\n");
      out.write("										서비스 이용약관</a><a target=\"_blank\" rel=\"nofollow\"\n");
      out.write("										href=\"https://www.ftc.go.kr/bizCommPop.do?wrkr_no=1208822325\"\n");
      out.write("										class=\"text term\" data-v-4e4965bd=\"\"> 사업자 정보확인 </a>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-content-list-term\" data-v-4e4965bd=\"\">\n");
      out.write("								<span class=\"text term-text\" data-v-4e4965bd=\"\">\n");
      out.write("									(주)브레이브모바일은 통신판매중개자로서 통신판매의 당사자가 아니며 개별 판매자가 제공하는 서비스에 대한 이행,\n");
      out.write("									계약사항 등과 관련한 의무와 책임은 거래당사자에게 있습니다. </span>\n");
      out.write("							</div>\n");
      out.write("							<ul class=\"col-content-guide\" data-v-4e4965bd=\"\">\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">상호명:(주)브레이브모바일 ·\n");
      out.write("									대표이사:KIM ROBIN H · 개인정보책임관리자:김태우 · 주소:서울특별시 강남구 테헤란로 415, L7\n");
      out.write("									강남타워 5층</li>\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">사업자등록번호:120-88-22325 ·\n");
      out.write("									통신판매업신고증:제 2021-서울강남-00551 호 · 직업정보제공사업 신고번호:서울청 제 2019-21호</li>\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">고객센터:1599-5319 ·\n");
      out.write("									이메일:support@soomgo.com</li>\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">Copyright ©Brave Mobile\n");
      out.write("									Inc. All Rights Reserved.</li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"col-content badge-list right\" data-v-4e4965bd=\"\">\n");
      out.write("							<a href=\"https://www.facebook.com/SoomgoKorea/\" target=\"_blank\"\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-facebook.svg\"\n");
      out.write("								alt=\"주니어 페이스북 계정\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://www.instagram.com/soomgo_official/\"\n");
      out.write("								target=\"_blank\" class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-instagram.svg\"\n");
      out.write("								alt=\"주니어 인스타그램\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://blog.naver.com/brave_mobile_mkt/\" target=\"_blank\"\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-naverblog.svg\"\n");
      out.write("								alt=\"주니어 블로그\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://post.naver.com/brave_mobile_mkt?isHome=1\"\n");
      out.write("								target=\"_blank\" class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-naverpost.svg\"\n");
      out.write("								alt=\"주니어 포스트\" data-v-4e4965bd=\"\"></a><a\n");
      out.write("								href=\"https://news.soomgo.com\" target=\"_blank\"\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-tistory.svg\"\n");
      out.write("								alt=\"주니어 스토리\" data-v-4e4965bd=\"\"></a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("	</div>\n");
      out.write("	<!-- 전체 div -->\n");
      out.write("	</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("<!-- <script src=\"/static/js/request-board-js/main-board.js\"></script> -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\n");
      out.write("<script src=\"https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("	let boards = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boards}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\n");
      out.write("	console.log(boards);\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/request-board-jym/timer.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/request-board-jym/addBoard.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /templates/request-board/request-board.jsp(277,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prev}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	                	<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/reqBoard.board?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startPage - 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"paging-choose\"><img src=\"/static/image/prev.png\" width=\"15px\"></a>\n");
          out.write("                	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /templates/request-board/request-board.jsp(280,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /templates/request-board/request-board.jsp(280,17) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startPage}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /templates/request-board/request-board.jsp(280,17) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${endPage}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                		");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                			");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                			");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                		");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /templates/request-board/request-board.jsp(282,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i eq page}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			                    <a href=\"javascript:void(0)\" class=\"paging paging-checked\">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</a>\n");
          out.write("                			");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /templates/request-board/request-board.jsp(283,82) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			                	<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/reqBoard.board?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"paging\">");
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</a>\n");
          out.write("                			");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /templates/request-board/request-board.jsp(286,105) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /templates/request-board/request-board.jsp(290,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${next}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/reqBoard.board?page=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${endPage + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"paging-choose\"><img src=\"/static/image/next.png\" width=\"15px\"></a>\n");
          out.write("                	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
